### ISSUE TITLE
QA: One-Click Subscribe

### ISSUE THREAD

**Issue by okaycj** [lookit/lookit-api#1362] opened 2024-03-11 17:31 UTC
### Summary
These are the instructions on how to QA One-Click Subscribe on the staging site (https://babieshelpingscience.com). 

### QA
The unsubscribe link should appear only in emails sent to participants. The study announcement emails are sent on a schedule and are not going to be able to be tested immediately.  

1. Auto 'study announcement' emails: If you've not already, sign up a child on staging and wait for the site to automatically send you an email. It would help to make sure that there is at least one 'live' study on staging and that the child you created qualifies for that study.
2. Custom emails from researchers: Go into a study that you can both participate in and send emails from. Participate in the study and then send yourself an email from the `message participants` view.

For both of these email types, click the unsubscribe link in the email body. 

With some email clients (e.g. gmail) you might see an unsubscribe link at the top of the email as well (a button near the to/from/subject info). That should also work.

After clicking 'unsubscribe' (either the link in the email or the button), you can verify the action by going to https://babieshelpingscience.com/account/email/ and checking that all checkboxes are unchecked. Before moving on, recheck all the boxes and save. This will help when you test unsubscribe on another email or using another method.

**Comment by becky-gilbert** [comment] 2024-03-19 22:15
Hi @okaycj @ianchandlercampbell, I tested this and the unsubscribe-all and feedback/question links at the bottom of the email are both working perfectly for me. I do have a few questions.

1. I noticed that the 3 links at the bottom of the participant-facing emails are all showing up on a single line:

![Screenshot 2024-03-19 at 2 52 56 PM](https://github.com/lookit/lookit-api/assets/9041788/dd6df871-bb10-4a8a-8816-0c6da07e133f)

Is it ok if I put in a PR to put these links on separate lines?

2. WRT to this unsubscribe-via-email method:

> With some email clients (e.g. gmail) you might see an unsubscribe link at the top of the email as well (a button near the to/from/subject info). That should also work.

I'm not seeing Gmail's 'unsubscribe' button at the top of the email, but I did find that clicking on the 'show details' arrow gives me the 'unsubscribe' field with a 'unsubscribe from this sender' link - see screenshots below. I clicked on the link and got a message (inside Gmail) about unsubscribing via email, and I clicked that, which gave me a confirmation message within the email client. I can see that Gmail sent an 'unsubscribe' email on my behalf.

I think the way we set this up was that we are going to monitor the lookit email for these unsubscribe emails and unsubscribe people manually, right? Can anyone verify that they received my unsubscribe email sent to lookit-bot@mit.edu? Can the 'bot' email address receive email? And does it matter that Gmail's confirmation message says that it's from 'Unknown'?

![Screenshot 2024-03-19 at 2 53 10 PM](https://github.com/lookit/lookit-api/assets/9041788/d62de2eb-f58c-41ef-a56d-8dbec3537e19)

![Screenshot 2024-03-19 at 2 53 28 PM](https://github.com/lookit/lookit-api/assets/9041788/f048e22b-8688-4915-915d-472bb9d0a193)

![Screenshot 2024-03-19 at 3 04 30 PM](https://github.com/lookit/lookit-api/assets/9041788/59d770c5-b3e0-4164-b6ea-9acc201c12d6)

**Comment by becky-gilbert** [comment] 2024-03-20 21:28
WRT \# 1 above - this was fixed in #1372. This is what the footer for participant-facing emails looks like now:

![Screenshot 2024-03-20 at 2 25 19 PM](https://github.com/lookit/lookit-api/assets/9041788/f4785710-d4f4-4bbe-bb20-50fc6026fd0e)

**Comment by ianchandlercampbell** [comment] 2024-03-21 02:29
Looks good! If possible I would like to see the unsubscribe button that
appears at the top of the email (I personally have found that useful for
other marketing emails as companies implemented this). I wonder if that
button is what we need, as most orgs had a footer link prior to the new
regulations?

**Comment by becky-gilbert** [comment] 2024-03-21 16:32
Yes, I think the unsubscribe regulations are related to unsubscribe-related email headers, which we've now included, rather than the link at the bottom of the message body.

I thought that gmail would show the 'unsubscribe' button at the top based on the inclusion of those headers, so I'm not sure why it isn't showing up. I can double check that our headers are correct and read up on when/how gmail adds that button, in case we're missing something.

**Comment by ianchandlercampbell** [comment] 2024-03-21 16:53
Thank you! I think that would be helpful.

Ian Chandler-Campbell, Ph.D.
Open-Source Community Manager, Children Helping Science
<https://childrenhelpingscience.com/>
Research Associate, Project GARDEN
<https://childrenhelpingscience.com/garden/scientists>
ianchandlercampbell.com
he/him/his

**Comment by ianchandlercampbell** [comment] 2024-03-26 16:32
@becky-gilbert that sounds like a plan! Reminds me of how Google also handles search indexing and "information cards" in search.

**Comment by ianchandlercampbell** [comment] 2024-03-26 16:52
It looks like the unsubscribe header is not working for some reason on mine-- I can test with a different lab email if that could be the root of the issue? Not sure why I wouldn't see the header (the footer seems to be functional, testing this next).

![Image](https://github.com/lookit/lookit-api/assets/75502403/5f4cf065-5de5-4c8d-88e1-125f8626bbc8)

**Comment by ianchandlercampbell** [comment] 2024-03-26 16:55
All unsubscribe combinations (logged in/logged out/already unsubscribed) seem to be operating as intended via the footer options.

**Closed** 2024-03-27 20:40 UTC
