### ISSUE TITLE
unchecking conditions, languages not respected in "all responses" downloads

### ISSUE THREAD

**Issue by lmoakes** [lookit/lookit-api#508] opened 2020-06-03 00:31 UTC
**Description**
Selecting the "Other participant data to include with responses" does not appear to filter what data are in the csv file.  Some subject characteristics are not listed.

**How to reproduce**
No matter which options are selected, the output looks the same.

**Expected behavior**
We expected that only the items selected would appear in the file. 

**Screenshots**

** Environment (OS, browser, branch, etc.):**
Mac OS 10.14.6; google Chrome.

**Additional context**
This is a problem for our IRB as they want us to not have access to some information, such as child name or any diagnosis (such as Autism).

I have attached screen shots of the options we selected and the output that was downloaded.

<img width="1175" alt="Screen Shot 2020-06-02 at 2 54 55 PM" src="https://user-images.githubusercontent.com/43151873/83578447-a8885c00-a4eb-11ea-8d3e-1732b129340b.png">
<img width="1028" alt="Screen Shot 2020-06-02 at 2 53 34 PM" src="https://user-images.githubusercontent.com/43151873/83578449-a9b98900-a4eb-11ea-9815-ced10b1ee65c.png">

**Comment by kimberscott** [comment] 2020-06-05 19:47
Can you confirm whether this is for the "child data" files rather than the response files? For the child data this is the intended behavior:
![Screen Shot 2020-06-05 at 3 32 10 PM](https://user-images.githubusercontent.com/9554627/83915722-cd760c80-a741-11ea-9ca4-33c35df5f7f0.png)

The checkboxes control what child/parent information you get _along with responses_. This can be minimized to just what would be needed to reproduce your analyses. The idea is that if you need the additional fields, you can download a "complete" child data file but store it separately (rather than dealing with another set of checkboxes etc.). But there's nothing available *only* in the child data file so no need to use it if you'd prefer not to.

Will that work for you? If so this is an issue of more clearly communicating what to expect, and UI suggestions are very welcome. (Maybe putting the checkboxes & affected file download buttons inside one outlined region would help as a visual cue?)

Child nicknames are also visible elsewhere (e.g. in the consent manager) but it sounds like the IRB is more concerned with whether you'll download/store them than whether you technically could. (We've found it's really helpful to have access to child nicknames during data collection because if a parent emails you, they expect to be able to say "well, my son Henry and I participated last Wednesday...")

**Comment by lmoakes** [comment] 2020-06-05 20:39
Hi Kim.

Thank you—we are getting it.

The issue we are having is that when we download the response summary (or whatever it is called), the child condition seems to always be included, even when we don’t check that box.  I think that is the bug.

This is the field my safety team/IRB really doesn’t want me to have because they are worried about HIPAA.

Lisa


Lisa M. Oakes
Professor, Department of Psychology
Faculty Researcher, Center for Mind and Brain
University of California, Davis
267 Cousteau Place
Davis, CA 95618

phone:  530 754-4523 OR
530 754-8304
Pronouns: she/her/hers

[cid:42BAFC46-1CBF-4718-B59D-003D4D71FFAA@cmb.ucdavis.edu]

On Jun 5, 2020, at 12:48 PM, Kim Scott <notifications@github.com<mailto:notifications@github.com>> wrote:



Can you confirm whether this is for the "child data" files rather than the response files? For the child data this is the intended behavior:
[Screen Shot 2020-06-05 at 3 32 10 PM]<https://user-images.githubusercontent.com/9554627/83915722-cd760c80-a741-11ea-9ca4-33c35df5f7f0.png>

The checkboxes control what child/parent information you get along with responses. This can be minimized to just what would be needed to reproduce your analyses. The idea is that if you need the additional fields, you can download a "complete" child data file but store it separately (rather than dealing with another set of checkboxes etc.). But there's nothing available only in the child data file so no need to use it if you'd prefer not to.

Will that work for you? If so this is an issue of more clearly communicating what to expect, and UI suggestions are very welcome. (Maybe putting the checkboxes & affected file download buttons inside one outlined region would help as a visual cue?)

Child nicknames are also visible elsewhere (e.g. in the consent manager) but it sounds like the IRB is more concerned with whether you'll download/store them than whether you technically could. (We've found it's really helpful to have access to child nicknames during data collection because if a parent emails you, they expect to be able to say "well, my son Henry and I participated last Wednesday...")

**Comment by lmoakes** [comment] 2020-06-11 17:37
Kim:

I am not at a medical school, but a lot of the research done here is done in the medical center. Many people (not us) have HIPAA waivers and use medical records in their research. I think this is a case of our review groups being overly cautious.

We will be all good as long as we can select to not get the information.

Thank you for helping us navigate these issues.

Lisa



Lisa M. Oakes
Professor, Department of Psychology
Faculty Researcher, Center for Mind and Brain
University of California, Davis
267 Cousteau Place
Davis, CA 95618

phone:  530 754-4523 OR
530 754-8304
Pronouns: she/her/hers

[cid:42BAFC46-1CBF-4718-B59D-003D4D71FFAA@cmb.ucdavis.edu]

On Jun 10, 2020, at 11:14 AM, Kim Scott <notifications@github.com<mailto:notifications@github.com>> wrote:



ah-hah, I see. I can replicate that here - it looks like the conditions and languages fields were misnamed and getting included regardless. Sorry about that - we'll have a fix up before launch!

I'm curious about the HIPAA concern though - are you at a medical school? The (counterintuitive) explanation I got from MIT's legal team was that whether you're a covered entity under HIPAA depends on your role as a healthcare provider and whether data is collected in the course of that relationship - not based on the exact nature of the data itself. https://privacyrights.org/consumer-guides/health-privacy-hipaa-basics has a good explanation of how narrowly it applies.

I'm all for minimizing information downloaded to protect participant privacy regardless, but suspect that worrying about HIPAA will cause unnecessary headaches down the line as a kid takes a puff of an inhaler on camera, or gets out their insulin pump, or has facial features associated with Down syndrome, and it becomes clear how much of a mess it would be to delineate what's "health information."

**Comment by kimberscott** [comment] 2020-06-12 17:27
Oh, that makes sense! Thanks for the background. Fix is actually done but will probably get merged in along with some other changes in progress.

**Comment by kimberscott** [comment] 2020-06-30 16:15
Fixed & extensive automated tests added :)

**Closed by kimberscott** 2020-06-30 16:15 UTC
Labels: bug
