### ISSUE TITLE
Missing videos - no pipeID

### ISSUE THREAD

**Issue by jchu10** [lookit/lookit-api#497] opened 2020-05-05 16:26 UTC
**Description**
Pipe ID is empty suggesting recording didn't happen. Participant completes a video as indicated by event data, but it doesn't show up in the experimenter interface. 

**How to reproduce**
[just a placeholder in case of repeated occurrence]

**Expected behavior**
Video should always record! All videos that are completed by the participant should correspond to a video available for download.

** Environment (OS, browser, branch, etc.):**
Production. Participant using Firefox 75.0 on Lenovo 10

**Additional context**
Preview event works just fine:
```
            "4-video-preview": {
                "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_4-video-preview_ce9167d9-e151-4085-8caa-6389b32a4035_1587325933507_891",
                "frameType": "DEFAULT",
                "videoList": [
                    "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_4-video-preview_ce9167d9-e151-4085-8caa-6389b32a4035_1587325933507_891"
                ],
                "eventTimings": [
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_4-video-preview_ce9167d9-e151-4085-8caa-6389b32a4035_1587325933507_891",
                        "eventType": "exp-video-preview:recorderReady",
                        "timestamp": "2020-04-19T19:52:13.518Z",
                        "streamTime": null
                    },
                    {
                        "pipeId": "",
                        "status": "connected",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_4-video-preview_ce9167d9-e151-4085-8caa-6389b32a4035_1587325933507_891",
                        "eventType": "exp-video-preview:videoStreamConnection",
                        "timestamp": "2020-04-19T19:52:14.394Z",
                        "streamTime": null
                    },
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_4-video-preview_ce9167d9-e151-4085-8caa-6389b32a4035_1587325933507_891",
                        "eventType": "exp-video-preview:recorder.hasCamAccess",
                        "timestamp": "2020-04-19T19:52:16.752Z",
                        "streamTime": 0,
                        "hasCamAccess": true
                    },
                    {
                        "pipeId": "vUWlWVvudS2zidKb7aIKL5e5SrDYlF4o",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_4-video-preview_ce9167d9-e151-4085-8caa-6389b32a4035_1587325933507_891",
                        "eventType": "exp-video-preview:startRecording",
                        "timestamp": "2020-04-19T19:52:18.743Z",
                        "streamTime": 0
                    },
                    {
                        "pipeId": "vUWlWVvudS2zidKb7aIKL5e5SrDYlF4o",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_4-video-preview_ce9167d9-e151-4085-8caa-6389b32a4035_1587325933507_891",
                        "eventType": "exp-video-preview:stoppingCapture",
                        "timestamp": "2020-04-19T19:53:43.516Z",
                        "streamTime": 84.85
                    },
                    {
                        "pipeId": "vUWlWVvudS2zidKb7aIKL5e5SrDYlF4o",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_4-video-preview_ce9167d9-e151-4085-8caa-6389b32a4035_1587325933507_891",
                        "eventType": "exp-video-preview:nextFrame",
                        "timestamp": "2020-04-19T19:53:44.069Z",
                        "streamTime": 84.85
                    },
                    {
                        "pipeId": "vUWlWVvudS2zidKb7aIKL5e5SrDYlF4o",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_4-video-preview_ce9167d9-e151-4085-8caa-6389b32a4035_1587325933507_891",
                        "eventType": "exp-video-preview:destroyingElement",
                        "timestamp": "2020-04-19T19:53:44.073Z",
                        "streamTime": 84.85
                    },
                    {
                        "pipeId": "vUWlWVvudS2zidKb7aIKL5e5SrDYlF4o",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_4-video-preview_ce9167d9-e151-4085-8caa-6389b32a4035_1587325933507_891",
                        "eventType": "exp-video-preview:destroyingElement",
                        "timestamp": "2020-04-19T19:53:44.073Z",
                        "streamTime": 84.85
                    }
                ],
                "generatedProperties": null
            }
```

On test trial, participant sees the stimuli, but we are not recording video. First trial was OK, but subsequent test trials were not, e.g.: 
```
"9-pref-phys-videos": {
                "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                "frameType": "DEFAULT",
                "videosShown": [
                    "https://s3.amazonaws.com/lookitcontents/exp-physics-final/stimuli/same/webm/sbs_same_A_B_box_c1_b1_NN.webm",
                    "https://s3.amazonaws.com/lookitcontents/exp-physics-final/stimuli/same/webm/sbs_same_B_A_box_c1_b1_NN.webm"
                ],
                "eventTimings": [
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                        "eventType": "exp-lookit-video:startAnnouncement",
                        "timestamp": "2020-04-19T20:01:29.106Z",
                        "streamTime": null
                    },
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                        "eventType": "exp-lookit-video:startAnnouncement",
                        "timestamp": "2020-04-19T20:01:29.107Z",
                        "streamTime": null
                    },
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                        "eventType": "exp-lookit-video:recorderReady",
                        "timestamp": "2020-04-19T20:01:29.108Z",
                        "streamTime": null
                    },
                    {
                        "pipeId": "",
                        "status": "connected",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                        "eventType": "exp-lookit-video:videoStreamConnection",
                        "timestamp": "2020-04-19T20:01:29.874Z",
                        "streamTime": null
                    },
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                        "eventType": "exp-lookit-video:startIntro",
                        "timestamp": "2020-04-19T20:01:30.385Z",
                        "streamTime": null
                    },
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                        "eventType": "exp-lookit-video:videoStopped",
                        "timestamp": "2020-04-19T20:01:35.999Z",
                        "streamTime": null,
                        "currentTask": "intro"
                    },
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                        "eventType": "exp-lookit-video:startTestVideo",
                        "timestamp": "2020-04-19T20:01:36.721Z",
                        "streamTime": null
                    },
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                        "eventType": "exp-lookit-video:startTestVideo",
                        "timestamp": "2020-04-19T20:01:36.927Z",
                        "streamTime": null
                    },
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                        "eventType": "exp-lookit-video:startTestVideo",
                        "timestamp": "2020-04-19T20:01:41.868Z",
                        "streamTime": null
                    },
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                        "eventType": "exp-lookit-video:startTestVideo",
                        "timestamp": "2020-04-19T20:01:46.270Z",
                        "streamTime": null
                    },
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                        "eventType": "exp-lookit-video:startTestVideo",
                        "timestamp": "2020-04-19T20:01:50.638Z",
                        "streamTime": null
                    },
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                        "eventType": "exp-lookit-video:startTestVideo",
                        "timestamp": "2020-04-19T20:01:55.040Z",
                        "streamTime": null
                    },
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                        "eventType": "exp-lookit-video:startTestVideo",
                        "timestamp": "2020-04-19T20:01:59.440Z",
                        "streamTime": null
                    },
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                        "eventType": "exp-lookit-video:nextFrame",
                        "timestamp": "2020-04-19T20:02:02.160Z",
                        "streamTime": null
                    },
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                        "eventType": "exp-lookit-video:destroyingElement",
                        "timestamp": "2020-04-19T20:02:02.171Z",
                        "streamTime": null
                    },
                    {
                        "pipeId": "",
                        "videoId": "videoStream_cfddb63f-12e9-4e62-abd1-47534d6c4dd2_9-pref-phys-videos_ce9167d9-e151-4085-8caa-6389b32a4035_1587326489096_912",
                        "eventType": "exp-lookit-video:destroyingElement",
                        "timestamp": "2020-04-19T20:02:02.171Z",
                        "streamTime": null
                    }
                ],
                "generatedProperties": null
            },
```

**Comment by kimberscott** [comment] 2020-05-26 13:13
Note: If reporting possible connected instances, please include (yes, this is all ok to post publicly):

    Study UUID & link to study detail page on experimenter interface
    Response UUID this makes it much easier to look up logs
    which frame(s) types, e.g. 'exp-lookit-observation'
    pipeId(s) of videos
    what the issue is (e.g., if videos are cut off, how long they should be per event data vs. how long they are) & any info from event data that might be relevant

**Comment by kimberscott** [comment] 2020-05-26 13:17
I suspect this may have been related to the user not selecting 'remember' regarding cam/mic permissions, which we've confirmed happening a few times and which would make sense with the first N frames recording video (esp. only the first test trial, after which the dialogue might be hidden).

**Comment by kimberscott** [comment] 2020-08-25 17:45
(closing, but if anyone sees this happen again please comment & reopen!)

**Closed by kimberscott** 2020-08-25 17:45 UTC
